### ISSUE TITLE
Questions on results of linear_vrnn

### ISSUE THREAD

**Issue by HashtagAsBridge** [Liang-Qiu/SVRNN-dialogues#10]
Excuse me, 
When I process your Linear_vrnn model with params in params.py, I got Structure Euclidean Distance about 0.24 and SCE about 4, could please give some guidance on how to get better results?
I followed the process: train linear_vrnn -> decode without test_batch -> interpretion
Thanks a lot for your help.

**Comment by Liang-Qiu** [comment]
Hi, I am not sure about your runtime details. Generally speaking, the bow-loss weight in hyperparameters has a significant impact on the performance.
